### ISSUE TITLE
pokemon health issues

### ISSUE THREAD

**Issue by vaniron** [LyquidQrystal/fightorflight#17]
Two issues reported via Discord:
1. **pokemon dont heal to full at start of the battle** so you can hit them outside of battle with sword and then finish them in battle which sounds like cheating - without the mod pokemon actually do start at full health everytime even when damaged so there is just some minor bug in Fight or Flight I guess.

2. **False swipe move in standard pokemon battle actually kills the pokemon** instead of leaving it with 1 hp. 
Maybe associated with health sync again?

**Comment by vaniron** [comment]
For the first issue we can either restore healing on battle start or prevent players from battling the pokemon if he is not at full health? Not sure which is better.

**Comment by LyquidQrystal** [comment]
1. I added mixins to sync the health when the pokemon entity is hurt or healed, I think it looks like an interesting feature when I tested it out a few weeks ago, so I just kept it. I can add a new config to disable the health sync for wild pokemon.
2. This is a bug, I've encountered it several times since I started a new save yesterday. To describe it more accurately, the pokemon will be killed if the health is very low(don't have to be 1) because the entity's health will be rounded down when the health is synchronized. I think keeping the entity's health to 1 if the pokemon's hp is still bigger than 0 might solve it.

**Comment by LyquidQrystal** [comment]
These problems should be solved now.

**Comment by vaniron** [comment]
Tested and looks fixed. Still not sure what that sync does? It changes pokemon health outside of battle based on its standard pokemon HP ?

**Comment by LyquidQrystal** [comment]
That's a long story to tell. To be short, it changes the pokemon's health when the entity got hurt/healed and changes the entity's health when the pokemon got hurt/healed.
I noticed that you mentioned that you're not sure about the hp sync part in the new pr and I checked it. The wild pokemon doesn't get healed. The pokemon itself is not hurt because the sync doesn't work on it when the value is set to true. The pokemon entity don't get healed, too. Besides, I'm not sure if the "pokemon outside of battle" will be confusing for someone. The other descriptions looks fine.
I wanted to sync the pokemon's health with the pokemon entity's health completely and add a more reasonable pokemon entity health(in Cobblemon, they just used the base stat, which means every pikachu uses the same entity health) at first.
Then I found updateMaxHealth in PokemonServerDelegate. I thought it was only used when the entity is initializing, so I write the code for the entity health here and wanted to try to find another way to sync the pokemon's health with the entity and failed. 
I could only add sync the entity's hp with the pokemon's hp by adding mixin to the entity.
I thought the pokemon's hp can't influence the entity's health and that's what I wrote in the readme.
However, I started playing a new save a few days ago and found that the pokemon's health can also influence the entity's health when it changes. I guess the level of my pokemon in the old save was too high that they just kill the pokemon before I could notice that. I don't know why the Cobblemon team chose to use updateMaxHealth every time a pokemon's hp changes but it just works, the sync seems to work fine on both sides except for the "False Swipe" bug before I fixed it.

**Comment by vaniron** [comment]
Well i think pokemon outside of battle is for many still more readable then pokemon entity. No idea how to phrase it bettter.
I know wild pokemon doesnt get healed technically but for players it does, they just see damaged entity and then full hp pokemon in battle.

**Comment by LyquidQrystal** [comment]
OK, I'll merge that

**Comment by vaniron** [comment]
Now False Swipe or any other move that leaves pokemon with very low HP doesnt kill him in battle but if player fleds the battle entity is killed.

**Comment by LyquidQrystal** [comment]
I'm not sure, the entity might disappear if the player fled but I haven't seen the death animation(or turning red), and I can't reproduce it stably.

**Comment by vaniron** [comment]
Best is to use level 100 pokemon with False swipe. I will test it more once home.
